server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓取自己的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
  instance:
    # 实例的标识id（Eureka主页可以看到）
    instance-id: orderService80
    # 显示ip地址。便于观看知道是哪台机器的实例
    prefer-ip-address: true
    # 下面两个是发送心跳和续约的时间
    # 开发的时候设置小点，保证服务关闭后注册中心能快速的剔除服务
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端在收到最后一次心跳后等待时间上限 ,单位为秒(默认是90秒),超时剔除服务
    lease-expiration-duration-in-seconds: 90

