spring:
  application:
    name: eureka-server

server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka

