spring:
  application:
    name: eureka-server

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002:7002/eureka


